// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_btDEXre1D7Qre3UH9zJIAnqbHAxj9g',
    appId: '1:784449642082:web:3fa10f83077c867c6afb3b',
    messagingSenderId: '784449642082',
    projectId: 'ecocycle-678a0',
    authDomain: 'ecocycle-678a0.firebaseapp.com',
    storageBucket: 'ecocycle-678a0.firebasestorage.app',
    measurementId: 'G-EL7BSW989Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49nZmHBRM1UJVAzJw7nLfSuYGysW_DM4',
    appId: '1:784449642082:android:8277da027a01d79f6afb3b',
    messagingSenderId: '784449642082',
    projectId: 'ecocycle-678a0',
    storageBucket: 'ecocycle-678a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLVkOOwKYlJiHhQeY8IoM2qc78ltlOGw4',
    appId: '1:784449642082:ios:a2efcd568352c69b6afb3b',
    messagingSenderId: '784449642082',
    projectId: 'ecocycle-678a0',
    storageBucket: 'ecocycle-678a0.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );
}
